version: 2.1
orbs:
  orb-tools: circleci/orb-tools@12.1
  buildevents: {}

filters: &filters
  tags:
    only: /.*/

release-filters: &release
  branches:
    ignore: /.*/
  tags:
    only: /^v[0-9]+\.[0-9]+\.[0-9]+$/

jobs:
  setup:
    docker:
      - image: cimg/base:stable
    steps:
      - buildevents/start_trace
      - buildevents/with_job_span:
          steps:
            - run: sleep 2
  watch:
    docker:
      - image: cimg/base:stable
    steps:
      - buildevents/watch_build_and_finish
  integration:
    docker:
      - image: cimg/base:stable
    steps:
      - buildevents/with_job_span:
          steps:
            - buildevents/add_context:
                field_name: arch
                field_value: uname -m
            - run: sleep 2

workflows:
  ci:
    jobs:
      - setup:
          filters: *filters
      - watch:
          requires: ['setup']
      - integration:
          requires: ['setup']
          filters: *filters

      # The orb must be re-packed for publishing
      - orb-tools/pack:
          filters: *release
      - orb-tools/publish:
          orb_name: honeycombio/buildevents
          vcs_type: << pipeline.project.type >>
          pub_type: production
          requires:
            - orb-tools/pack
            - integration
          context: orb-publishing
          filters: *release
